name: Backend Role Service CI/CD

on:
  push:
    branches: [main]

jobs:
  setup:
    name: Setup Node.js
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm install

  lint:
    name: Lint
    needs: setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install deps
        run: npm ci || npm install

      - name: Install ESLint deps
        run: npm i -D eslint@^9 @eslint/js@^9 || true

      - name: Disable ESLint matchers
        run: |
          echo "::remove-matcher owner=eslint-compact::" || true
          echo "::remove-matcher owner=eslint-stylish::" || true

      - name: Run ESLint to JSON
        env:
          REPORT_PATH: ${{ github.workspace }}/backend/reports/eslint-report.json
        run: |
          mkdir -p "$(dirname "$REPORT_PATH")"
          npx eslint . --ext .js,.jsx,.ts,.tsx --format json -o "$REPORT_PATH" || true
          [ -s "$REPORT_PATH" ] || echo "[]" > "$REPORT_PATH"

      - name: Lint summary
        env:
          REPORT_PATH: ${{ github.workspace }}/backend/reports/eslint-report.json
        run: |
          node -e "const fs=require('fs');let a=[];try{a=JSON.parse(fs.readFileSync(process.env.REPORT_PATH,'utf8'))}catch{};const e=a.reduce((s,f)=>s+f.errorCount,0);const w=a.reduce((s,f)=>s+f.warningCount,0);const fct=a.length;console.log(`ESLint completed · files: ${fct}, errors: ${e}, warnings: ${w}`);"

      - name: Upload ESLint report
        uses: actions/upload-artifact@v4
        with:
          name: eslint-report-backend
          path: backend/reports/eslint-report.json

  unit-test:
    name: Run Backend Unit Tests
    needs: [setup, lint]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: backend/package-lock.json
      - run: npm ci
      - run: npm test

  integration-test:
    name: Run Integration Tests
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install
      working-directory: backend

    - name: Start backend server
      run: nohup node app.js & sleep 5
      working-directory: backend

    - name: Run Postman tests with Newman
      run: |
          echo "Running Postman tests with newman..."
          newman run postman/smartrpd.postman_collection.json \
            -e postman/smartrpd-env.postman_environment.json \
            --reporters cli \
            --export-cookie-jar ./cookies.json \
            --insecure

  codeql:
    name: Security Analysis with CodeQL
    needs: [unit-test, integration-test]
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - uses: github/codeql-action/analyze@v3

  dockerize:
    name: Docker Build
    needs: codeql
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t role-backend ./backend

  deploy:
    name: Deploy to GCP Backend VM
    needs: dockerize
    runs-on: ubuntu-latest
    steps:
      - name: SSH to GCP and deploy backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BACKEND_VM_IP }}
          username: ${{ secrets.BACKEND_VM_USER }}
          key: ${{ secrets.BACKEND_VM_SSH_KEY }}
          script: |
            cd ~/role-management-backend
            git pull origin main
            docker stop role-backend || true
            docker rm role-backend || true
            docker build -t role-backend ./backend
            docker run -d --name role-backend -p 3001:3001 role-backend
